### ISSUE TITLE
Parallel testing and/or publishing

### ISSUE THREAD

**Issue by vladgh** [puppetlabs/puppet-in-docker#9]
Would you be interested in leveraging the Travis CI's parallel builds across virtual machines?

``` YML
env:
  - IMAGE=puppet-agent-alpine
  - IMAGE=puppet-agent-centos
  - etc.
script: bundle exec rake ${IMAGE}:spec
```

This will iterate through all image names and create an individual build job for each.
The only downside I see to this method is that you have to hardcode each image name in the `$IMAGE` environment variable.

As an example, his is my [.travis.yml](https://github.com/vghn/puppet-docker/blob/master/.travis.yml) and [build example](https://travis-ci.org/vghn/puppet-docker/builds/152794724)

PS: My example is heavily based on your repo; thank you!
